# URL from which to load CSV data. This can be changed to point to a new data source as needed.
dataSourceUrl: "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjT0b21zy9tB1SzvkQw4MTrGL8HvUAIjEn_HJeogiZkto8Ia3MNyIVevHv84z9AtZ-rPAidI4r_MyU/pub?gid=0&single=true&output=csv"

# Number of characters to show in the item description before truncating. This value can be adjusted to show more or less text.
descriptionLength: 400

# List of facets that can be used to filter items. New facets can be added or existing ones removed as needed.
activeFacets:
  - "TIPO"
  - "TAGS"